// This file was generated by lezer-generator. You probably shouldn't edit it.
import {Parser} from "lezer"
import {NodeProp} from "lezer"
const spec_idx = {__proto__:null,Schritt:68, LinksDrehen:70, RechtsDrehen:72, Hinlegen:74, Aufheben:76, MarkeSetzen:78, "MarkeLöschen":80, Ton:82, Beenden:84, Warten:86, schnell:88, langsam:90, wiederhole:92, solange:94, nicht:96, IstWand:98, NichtIstWand:100, IstZiegel:102, NichtIstZiegel:104, IstMarke:106, NichtIstMarke:108, IstOsten:110, "IstSüden":112, IstWesten:114, IstNorden:116, mal:120, endewiederhole:122, wenn:124, dann:126, sonst:128, endewenn:130, wahr:132, falsch:134, Anweisung:136, endeAnweisung:138, Bedingung:140, endeBedingung:144}
export const parser = Parser.deserialize({
  version: 13,
  states: ")fQYQPOOOOQO'#C_'#C_OOQO'#C`'#C`OOQO'#Cb'#CbO!gQPO'#CaOOQO'#Cj'#CjO#dQPO'#CiOOQO'#Cn'#CnOOQO'#C|'#C|OOQO'#Cp'#CpO#kQPO'#CoOOQO'#Ct'#CtO#pQQO'#CsOOQO'#Cw'#CwQYQPOOOOQO'#Cc'#CcOOQO'#Cf'#CfO#uQPO,58{O%RQPO,58{OOQO'#Ce'#CeOOQO'#Cd'#CdO%WQPO'#CdOOQO'#Ck'#CkO%xQPO,59TO'VQPO,59TOOQO'#Cq'#CqO'[QPO,59ZOOQO'#Cu'#CuO(fQPO,59_OOQO-E6u-E6uOOQO'#Cx'#CxO)pQPO1G.gOOQO'#Ch'#ChOOQO1G.g1G.gO)pQPO1G.gOOQO'#Cg'#CgOOQO,59O,59OO%xQPO1G.oOOQO'#Cl'#ClOOQO'#Cm'#CmOOQO1G.o1G.oO*zQPO1G.oO%xQPO1G.oO'[QPO1G.uOOQO'#Cr'#CrOOQO1G.u1G.uO(fQPO1G.yOOQO'#Cv'#CvOOQO1G.y1G.yOOQO-E6v-E6vOOQO7+$R7+$RO)pQPO7+$ROOQO7+$Z7+$ZO*zQPO7+$ZO*zQPO7+$ZO%xQPO7+$ZOOQO7+$a7+$aOOQO7+$e7+$eOOQO<<Gm<<GmO*zQPO<<GuOOQO<<Gu<<GuO*zQPO<<GuOOQOAN=aAN=aO*zQPOAN=aOOQOG22{G22{",
  stateData: ",U~OPOSoOS~OqWOrPOsPOtPOuPOvPOwPOxPOyPOzPO{PO|QO}QO!ORO!`TO!dVO!eVO!fXO!hZO~O!P_O!]`O~O!QcO!RdO!SdO!TdO!UdO!VdO!WdO!XdO!YdO!ZdO![dO~O!afO~P!oOqiO~O!ikO~OqWOrPOsPOtPOuPOvPOwPOxPOyPOzPO{PO|QO}QO!ORO!_pO!`TO!dVO!eVO~P!oO!^sO~O!RtO!StO!TtO!UtO!VtO!WtO!XtO!YtO!ZtO![tO~OqWOrPOsPOtPOuPOvPOwPOxPOyPOzPO{PO|QO}QO!ORO!`TO!bvO!cwO!dVO!eVO~O!afO~OqWOrPOsPOtPOuPOvPOwPOxPOyPOzPO{PO|QO}QO!ORO!`TO!dVO!eVO!g|O~OqWOrPOsPOtPOuPOvPOwPOxPOyPOzPO{PO|QO}QO!ORO!`TO!dVO!eVO!j!PO~OqWOrPOsPOtPOuPOvPOwPOxPOyPOzPO{PO|QO}QO!ORO!_pO!`TO!dVO!eVO~OqWOrPOsPOtPOuPOvPOwPOxPOyPOzPO{PO|QO}QO!ORO!`TO!cwO!dVO!eVO~O",
  goto: "&qqPPPrrr!Y!p!s!y!}#Q#Tr#_#u#{$Vr$k$o$s$v$k$|%Q%T%Z%aPPP&XyWO^agjloruyz{!O!T!V!W!X!]!_!aySO^agjloruyz{!O!T!V!W!X!]!_!aRaSQhURraTeUaRbSRrbQqaS!SorR![!TyUO^agjloruyz{!O!T!V!W!X!]!_!aQgURzhQygS!VuzR!_!XQxgU!UuyzU!^!V!W!XS!`!]!_R!b!aT]O^TYO^RjYQ}jR!Y{T[O^Rl[Q!QlR!Z!OQ^ORm^QoaQugQ{jQ!Olb!Rou{!O!T!W!X!]!aQ!TrQ!WyQ!XzQ!]!VR!a!_S]O^unagjloruyz{!O!T!V!W!X!]!_!a",
  nodeNames: "⚠ Comment Program Command SpecialCommand Repeat RepeatStart RepeatWhileKey Condition Not Times RepeatTimesKey RepeatEnd IfThen IfKey ThenKey ElseKey IfEndKey TF Cmd CmdStart CmdName CmdEnd Cond CondStart CondName CondEnd",
  maxTerm: 72,
  nodeProps: [
    [NodeProp.closedBy, 6,"RepeatEnd",14,"IfEndKey",20,"CmdEnd",24,"CondEnd"]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 2,
  tokenData: "#l~RXXYnYZn]^npqn!Q![!P!c!}!X#R#S!X#T#o!X#o#p#Z~sSo~XYnYZn]^npqn~!UP!]~!Q![!PR!`UqP!iQxy!ryz!r!Q![!X!c!}!X#R#S!X#T#o!XQ!wU!iQxy!ryz!r!Q![!r!c!}!r#R#S!r#T#o!r~#^RO#q#Z#q#r#g#r~#Z~#lOP~",
  tokenizers: [0, 1],
  topRules: {"Program":[0,2]},
  specialized: [{term: 33, get: value => spec_idx[value] || -1}],
  tokenPrec: 0
})
