// This file was generated by lezer-generator. You probably shouldn't edit it.
import {Parser} from "lezer"
import {NodeProp} from "lezer"
const spec_idx = {__proto__:null,Schritt:56, LinksDrehen:58, RechtsDrehen:60, Hinlegen:62, Aufheben:64, MarkeSetzen:66, "MarkeLöschen":68, Beenden:70, Unterbrechen:72, wiederhole:74, solange:76, IstWand:78, NichtIstWand:80, IstZiegel:82, NichtIstZiegel:84, IstMarke:86, NichtIstMarke:88, mal:92, endewiederhole:94, wenn:96, dann:98, sonst:100, endewenn:102, Anweisung:104, endeAnweisung:106}
export const parser = Parser.deserialize({
  version: 13,
  states: "'zQYQPOOOOQO'#C_'#C_OOQO'#Ca'#CaO!TQPO'#C`OOQO'#Ch'#ChO!qQPO'#CgOOQO'#Cl'#ClOOQO'#Cv'#CvOOQO'#Cn'#CnO!xQPO'#CmOOQO'#Cq'#CqQYQPOOOOQO'#Cb'#CbOOQO'#Cd'#CdO!}QPO,58zO#zQPO,58zOOQO'#Cc'#CcOOQO'#Ci'#CiO$PQPO,59RO$}QPO,59ROOQO'#Co'#CoO%SQPO,59XOOQO-E6o-E6oOOQO'#Cr'#CrO%}QPO1G.fOOQO'#Cf'#CfOOQO1G.f1G.fO%}QPO1G.fOOQO'#Ce'#CeO$PQPO1G.mOOQO'#Cj'#CjOOQO'#Ck'#CkOOQO1G.m1G.mO&xQPO1G.mO$PQPO1G.mO%SQPO1G.sOOQO'#Cp'#CpOOQO1G.s1G.sOOQO-E6p-E6pOOQO7+$Q7+$QO%}QPO7+$QOOQO7+$X7+$XO&xQPO7+$XO&xQPO7+$XO$PQPO7+$XOOQO7+$_7+$_OOQO<<Gl<<GlO&xQPO<<GsOOQO<<Gs<<GsO&xQPO<<GsOOQOAN=_AN=_O&xQPOAN=_OOQOG22yG22y",
  stateData: "'s~OPOSiOS~OkUOlPOmPOnPOoPOpPOqPOrPOsPOtPOuQO!QSO!UWO~Ov[O}]O~Ow`Ox`Oy`Oz`O{`O|`O~O!RaO~P!]OkdO~OkUOlPOmPOnPOoPOpPOqPOrPOsPOtPOuQO!PiO!QSO~P!]O!OlO~OkUOlPOmPOnPOoPOpPOqPOrPOsPOtPOuQO!QSO!SnO!ToO~O!RaO~OkUOlPOmPOnPOoPOpPOqPOrPOsPOtPOuQO!QSO!VtO~OkUOlPOmPOnPOoPOpPOqPOrPOsPOtPOuQO!PiO!QSO~OkUOlPOmPOnPOoPOpPOqPOrPOsPOtPOuQO!QSO!ToO~O",
  goto: "%|kPPPll!Q!f!i!o!r!ul#P#e#k#ul$Z$_$c$f$l$rPPP%fuVOZ^behkmqrsxz{|!P!R!TuROZ^behkmqrsxz{|!P!R!TR^RQcTRk^R_RRk_Qj^SwhkR!OxuTOZ^behkmqrsxz{|!P!R!TQbTRrcQqbSzmrR!R|QpbUymqrU!Qz{|S!S!P!RR!U!TTYOZTXOZReXQueR}sQZORfZQh^QmbQse`vhmsx{|!P!TQxkQ{qQ|rQ!PzR!T!RSYOZqg^behkmqrsxz{|!P!R!T",
  nodeNames: "⚠ Comment Program Command Repeat RepeatStart RepeatWhileKey Condition Times RepeatTimesKey RepeatEnd IfThen IfKey ThenKey ElseKey IfEndKey CustomRef Cmd CmdStart CmdName CmdEnd",
  maxTerm: 53,
  nodeProps: [
    [NodeProp.closedBy, 5,"RepeatEnd",12,"IfEndKey",18,"CmdEnd"]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 2,
  tokenData: "#y~R`XY!TYZ!T]^!Tpq!T!Q![!f!c!}!n#R#S!n#T#o!n#o#p#f%[%]!n%n%o!n%t%u!n%w%x!n%|%}!n&`&a!n&f&g!n~!YSi~XY!TYZ!T]^!Tpq!T~!kP}~!Q![!f~!sZk~!Q![!n!c!}!n#R#S!n#T#o!n%[%]!n%n%o!n%t%u!n%w%x!n%|%}!n&`&a!n&f&g!n~#kRP~O#q#f#q#r#t#r~#f~#yOP~",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  specialized: [{term: 27, get: value => spec_idx[value] || -1}],
  tokenPrec: 0
})
