// This file was generated by lezer-generator. You probably shouldn't edit it.
import {Parser} from "lezer"
import {NodeProp} from "lezer"
const spec_idx = {__proto__:null,Hinlegen:60, Schritt:62, LinksDrehen:64, RechtsDrehen:66, Aufheben:68, wiederhole:70, immer:72, solange:74, mal:86, endewiederhole:90, wenn:92, dann:94, sonst:96, endewenn:98, Anweisung:100, endeAnweisung:102}
export const parser = Parser.deserialize({
  version: 13,
  states: "+|OVQPOOOOQO'#Cq'#CqOVQPOOOOQO'#C_'#C_OOQO'#Ca'#CaOwQPO'#C`OOQO'#Ci'#CiOwQPO'#ChOOQO'#Cx'#CxOOQO'#Cn'#CnOwQPO'#CmO|QPO'#CwQwQPOOOOQO-E6o-E6oO!XQPO,58zO!gQQO,59SO!xQPO,59XOVQPO'#CsO#QQPO,59cQwQPOOOOQO'#Cb'#CbOOQO'#Cc'#CcOOQO'#Ce'#CeOwQPO1G.fOwQPO1G.fOwQPO1G.fOOQO'#Cd'#CdOwQPO1G.nOOQO'#Co'#CoOwQPO1G.sOOQO,59_,59_OOQO-E6q-E6qO#]QPO7+$QO!gQQO7+$QO#zQPO7+$QO$SQPO7+$YO$[QPO7+$_O$cQPO<<GlO%TQPO'#DYOwQPO<<GlOwQPO<<GlOOQO'#Cf'#CfOOQO'#Cj'#CjOwQPO<<GtOOQO'#Cp'#CpOOQO<<Gy<<GyOwQPO<<GyOOQO'#Cg'#CgOOQOAN=WAN=WO#]QPO'#CrO%]QPO,59tO%eQPOAN=WO#]QPOAN=WO%mQPOAN=`O%tQPOAN=eOOQO,59^,59^OOQO-E6p-E6pOOQOG22rG22rO$cQPOG22rOwQPOG22rO%|QPOG22zOOQO'#Cl'#ClOOQOG22zG22zOwQPOG22zOOQOG23PG23POOQOLD(^LD(^O%eQPOLD(^OOQO'#Ck'#CkOwQPOLD(fO&qQPOLD(fOOQO!$'Kx!$'KxO%mQPO!$'LQO&yQPO!$'LQOOQO!$'LQ!$'LQOOQO!)9Al!)9AlO&tQPO!)9AlOwQPO!)9AlOOQO!.K7W!.K7WO%mQPO!.K7WOOQO!4/,r!4/,rO&tQPO!4/,rOOQO!9A!^!9A!^O'UQPO'#DYO'^QPO,59t",
  stateData: "'f~OPOS~OjPOmWOnROoROpROqROrROsSO!OUO!SXO~OjPO~OjPOhkXjkX~OjPOtdOueOzfO~OjPOvjOwjOxjOyjO~OjPOmlO~OjPOhkajka~OjPOmWOnROoROpROqROrROsSO!OUO~OjPO{yO~OjPO!PzO~O!T|O~P#]O}!POjecmecnecoecpecqecrecsec!Oec~OjPOj|X~OjPOj|a~OjPO}!PO~O!R!_O~P#]OjPO!T|O~O!Q!eOjecmecnecoecpecqecrecsec!Oec!Rec~OjPO!R!_O~O!Q!eOjec!Rec~OjPO!R|X~OjPO!R|a~O",
  goto: "'t}PPP!O!O![!h!k!n!t!w!z!O#W#d#g#m$P$W$]$`$f&h&rPPP&x&|PPPPPPPPPPPPPPP'beWOQapt!R!U!V!i!peTOQapt!R!U!V!i!pRg^Rh^Qk_RxqRi^RxrQ!QuQ!Z!TQ!c![R!h!deVOQapt!R!U!V!i!pR{sQ!f!^R!n!jQ!`!VQ!k!gQ!l!iQ!o!mQ!q!pR!s!rSZOQRnaVYOQaRm`Q}tR!b!WQQOp]Q^_`acqrst!R!T!W!d!i!pQ^TQ_VQ`YSaZbQc[QpgQqhQriQskQtmQupW!Rv!S!t!uQ!TwQ!UxQ!V{Q!W!OQ![!UQ!^!VQ!d!]Q!g!aQ!i!fQ!j!gR!p!nQ!SvS!Y!S!uR!u!tQbZRobT[OQSZOQQnaWvpt!U!VQ!X!RT!t!i!pQwpQ!OtQ!]!UQ!a!VQ!m!iR!r!p",
  nodeNames: "⚠ Comment Program Command Repeat RepeatStart RepeatAlwaysKey RepeatWhileKey Condition Times RepeatTimesKey RepeatEnd IfThen IfKey ThenKey ElseKey IfEndKey Cmd CmdStart CmdName CmdEnd",
  maxTerm: 51,
  nodeProps: [
    [NodeProp.closedBy, 5,"RepeatEnd",13,"IfEndKey",18,"CmdEnd"]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 3,
  tokenData: "2e~R]XYzYZz]^zpqz!Q![!]!c!k!e!k!l!{!l!p!e!p!q)[!q!}!e#R#S!e#T#o!e#o#p2S~!PSj~XYzYZz]^zpqz~!bPz~!Q![!]P!jSmP!Q![!v!c!}!e#R#S!e#T#o!eP!{OmPR#QUmP!Q![!v!c!}!e#R#S!e#T#g!e#g#h#d#h#o!eR#iUmP!Q![!v!c!}!e#R#S!e#T#h!e#h#i#{#i#o!eR$QVmP!Q![!v!c!y!e!y!z$g!z!|!e!|!}&`#R#S!e#T#o!eR$lTmP!Q![!v!c!}!e#R#S!e#T#U${#U#o!eR%QUmP!Q![!v!c!}!e#R#S!e#T#b!e#b#c%d#c#o!eR%iUmP!Q![!v!c!}!e#R#S!e#T#W!e#W#X%{#X#o!eR&SSvQmP!Q![!v!c!}!e#R#S!e#T#o!eR&eUmP!Q![!v!c!}!e#R#S!e#T#]!e#]#^&w#^#o!eR&|UmP!Q![!v!c!}!e#R#S!e#T#X!e#X#Y'`#Y#o!eR'eUmP!Q![!v!c!}!e#R#S!e#T#Z!e#Z#['w#[#o!eR'|UmP!Q![!v!c!}!e#R#S!e#T#X!e#X#Y(`#Y#o!eR(eUmP!Q![!v!c!}!e#R#S!e#T#`!e#`#a(w#a#o!eR)OSxQmP!Q![!v!c!}!e#R#S!e#T#o!eR)aUmP!Q![!v!c!}!e#R#S!e#T#]!e#]#^)s#^#o!eR)xUmP!Q![!v!c!}!e#R#S!e#T#V!e#V#W*[#W#o!eR*aUmP!Q![!v!c!}!e#R#S!e#T#[!e#[#]*s#]#o!eR*xUmP!Q![!v!c!}!e#R#S!e#T#h!e#h#i+[#i#o!eR+aUmP!Q![!v!c!k!e!k!l+s!l!}!e#R#S!e#T#o!eR+xUmP!Q![!v!c!}!e#R#S!e#T#g!e#g#h,[#h#o!eR,aUmP!Q![!v!c!}!e#R#S!e#T#h!e#h#i,s#i#o!eR,xVmP!Q![!v!c!y!e!y!z-_!z!|!e!|!}/W#R#S!e#T#o!eR-dTmP!Q![!v!c!}!e#R#S!e#T#U-s#U#o!eR-xUmP!Q![!v!c!}!e#R#S!e#T#b!e#b#c.[#c#o!eR.aUmP!Q![!v!c!}!e#R#S!e#T#W!e#W#X.s#X#o!eR.zSwQmP!Q![!v!c!}!e#R#S!e#T#o!eR/]UmP!Q![!v!c!}!e#R#S!e#T#]!e#]#^/o#^#o!eR/tUmP!Q![!v!c!}!e#R#S!e#T#X!e#X#Y0W#Y#o!eR0]UmP!Q![!v!c!}!e#R#S!e#T#Z!e#Z#[0o#[#o!eR0tUmP!Q![!v!c!}!e#R#S!e#T#X!e#X#Y1W#Y#o!eR1]UmP!Q![!v!c!}!e#R#S!e#T#`!e#`#a1o#a#o!eR1vSyQmP!Q![!v!c!}!e#R#S!e#T#o!e~2VRO#q2S#q#r2`#r~2S~2eOP~",
  tokenizers: [0, 1],
  topRules: {"Program":[0,2]},
  specialized: [{term: 29, get: value => spec_idx[value] || -1}],
  tokenPrec: 0
})
