export const deStrings = {
  overview: {
    profile: 'Profil',
    editor: 'Aufgaben-Editor',
    save: 'Fortschritt speichern',
    saveTooltip: 'Als Datei herunterladen',
    load: 'Fortschritt laden',
    loadTooltip: 'Aus einer Datei laden',
    gameState: 'spielstand',
    playground: 'Spielwiese',
    imprint: 'Impressum',
    privacy: 'Datenschutz',
    showAll: 'Liste aller Aufgaben',
    closeShowAll: 'Liste aller Aufgaben schließen',
    game: 'Mini-Spiel',
    storeOnDevice: 'Fortschritt automatisch speichern?',
    later: 'später',
    docs: 'Dokumentation',
    path: 'Selbst-Lern-Pfad',
    startNow: 'Jetzt starten',
    syncProgress: 'Fortschritt speichern',
    syncTitle: 'Dein Fortschritt in guten Händen',
    syncBody:
      'Gelösten Aufgaben und deine Programme werden ab jetzt in diesem Browser automatisch gespeichert und sind auch nach dem Schließen des Fensters weiter verfügbar.',
    donate: 'Spenden',
    learningPath: 'Lernpfad',
    freePractice: 'freies Üben',
    loadQuestFromFile: 'Aufgabe aus Datei laden',
    welcome1: 'Willkommen 👋 entdecke hier',
    welcome2: 'die Welt der Algorithmen!',
    drawFigure1: 'Figur',
    drawFigure2: 'zeichnen',
    figureGallery: 'Figuren-Galerie',
    taskGallery: '💫 Aufgaben-Galerie',
    teacherMaterial: 'Material für Lehrkräfte',
    videoExplanations: 'Video-Erklärungen',
    switchToGerman: 'Zur deutsche Version',
    newFigureAvailable: 'Neue Figur verfügbar:',
    close: 'schließen',
    loadFigure: 'Laden',
    greeting: 'Hallo, {name}!',
    playgroundDescription: 'Programmiere frei und baue dein Herzensprojekt.',
  },
  nameModal: {
    title: 'Herzlich Willkommen!',
    invite: 'Wie heißt du?',
    hint: 'Dein Name wird öffentlich angzeigt.',
    random: 'zufälliger Name',
    start: 'Loslegen!',
    placeholder: 'Dein Name...',
  },
  ide: {
    backToOverview: 'zurück zur Übersicht',
    save: 'Bearbeitung speichern',
    load: 'Bearbeitung laden',
    blocks: 'Blöcke',
    structogram: 'Struktogramm',
    welcome:
      'Herzlich Willkommen! Hier lernst du Schritt für Schritt die Welt von Karol kennen. Das Tutorial zeigt dir die ersten Grundlagen für die Programmierung.',
    tutorialButton: 'Tutorial anzeigen',
    start: 'Start',
    stop: 'Stopp',
    ready: 'bereit',
    not: 'nicht',
    completed: 'erfüllt',
    back: 'zurück',
    assignment: 'Auftrag',
    assignments: 'Aufträge',
    continue: 'Weiter',
    done: 'Fertig',
    continueAll: 'weiter (alle Aufträge testen)',
    steps: 'Schritte pro Sekunde',
    programError: 'Programm unvollständig',
    loading: 'Programm wird eingelesen ...',
    running: 'Programm wird ausgeführt',
    error: 'Fehler',
    endOfRun: 'Ausführung beendet',
    aborted: 'abgebrochen',
    clear: 'Ausgabe leeren',
    taskCompleted: 'abgeschlossen',
    showDescription: 'Beschreibung einblenden',
    thereAreErrors:
      'Folgende Probleme sind beim Einlesen des Programms aufgetreten:',
    close: 'Schließen',
    connectAll:
      'Blöcke sind nicht zusammenhängend. Verbinde die Blöcke zu einem Programm oder nutze den Hauptprogramm-Block.',
    multipleMains:
      'Mehr als ein Hauptprogramm - erwarte höchstens ein Hauptprogramm.',
    stay: 'bleiben',
    exit: 'weiter',
    read: 'Lies die Anleitung',
    language: 'Sprache',
    problems: 'Es sind folgende Probleme aufgetreten',
    line: 'Zeile',
    preview: 'Auftragsvorschau',
    step: 'Einzelschritt',
    continueProgram: 'weiter',
    blockExplainer: 'Ziehe Blöcke auf die Arbeitsfläche und verbinde sie.',
    menu: 'Menü',
    openInEditor: 'Im Editor öffnen',
    resetCode: 'Code zurücksetzen',
    program: 'Programm',
    world: 'Welt',
    ok: 'OK',
    tourStepDrag:
      'Legen wir los! Ziehe den Befehl „Schritt" auf die Arbeitsfläche',
    tourClickStart: 'Klicke auf Start!',
    tourComplete:
      'Sehr gut! Schreibe das Programm fertig: Gehe mit Karol zwei Schritte und lege einen Ziegel.',
    fixProblemsFirst: 'Bitte behebe zuerst Probleme!',
    originalLanguage: 'Die Original-Sprache von Robot Karol',
    cheatsheet: 'Spickzettel',
    variables: 'Variablen:',
    mainProgram: 'Hauptprogramm',
    problemsInProgram: 'Probleme im Programm',
    emptyProgram: 'Leeres Programm',
    structogramError: 'Fehler bei der Generierung des Struktogramms.',
    repeatForever: 'wiederhole immer',
    repeatWhile: 'wiederhole solange',
    repeat: 'wiederhole',
    times: 'mal',
    view2D: '2D-Ansicht',
    fullscreen: 'Vollbild',
    keys: 'Tasten:',
    manualStep: 'Schritt',
    manualTurnLeft: 'LinksDrehen',
    manualTurnRight: 'RechtsDrehen',
    manualBack: 'Zurück',
    questPromptContinue: 'weiter',
    copiedToClipboard: 'In Zwischenablage kopiert!',
  },
  profile: {
    title: 'Profil',
    close: 'Schließen',
    username: 'Benutzername',
    noname: 'noch kein Name gesetzt',
    solved: 'Gelöste Aufgaben',
    of: 'von',
    reset: 'Fortschritt zurücksetzen',
    resetConfirm:
      'Fortschritt jetzt zurücksetzen? Die Aktion kann nicht rückgängig gemacht werden.',
  },
  imprint: {
    title: 'Impressum',
    close: 'Schließen',
  },
  crash: {
    invalidMove: 'Aua! Karol ist gegen eine Wand gelaufen.',
    invalidHeight: 'Karol kann diese Höhe nicht überwinden.',
    invalidBrick: 'Karol kann hier keinen Ziegel aufstellen.',
    maxHeight: 'Maximale Stapelhöhe erreicht.',
    invalidPick: 'Karol kann hier keine Ziegel aufheben.',
    noBricks: 'Keine Ziegel zum Aufheben',
    invalidBlock: 'Karol kann hier keinen Quader aufstellen.',
    noBlockOnBrick: 'Karol kann keinen Quader auf Ziegel stellen.',
    noBlockOnMark: 'Karol kann keinen Quader auf eine Marke stellen.',
  },
  quest: {
    warn: '',
  },
  editor: {
    edit: 'Bearbeiten',
    preview: 'Vorschau',
    leave: 'Editor verlassen',
    leaveWarning: 'Beachte dass die Daten nicht gespeichert werden. Verlassen?',
    title: 'Titel der Aufgabe',
    description: 'Beschreibe, um was es bei der Aufgabe geht ...',
    newTask: 'Neuer Auftrag',
    test: 'Testen',
    editWorld: 'Welt bearbeiten',
    up: 'hoch',
    down: 'runter',
    duplicate: 'Auftrag duplizieren',
    delete: 'Auftrag löschen',
    addTask: 'Auftrag hinzufügen',
    publish: 'Aufgabe freigeben',
    loadFrom: 'Aus Vorlage laden',
    load: 'Laden',
    close: 'Schließen',
    fromCode: 'Aus freigegebener Aufgabe, gib den vierstelligen Code ein',
    fromQuest: 'Aus einer vorhandenen Aufgabe',
    pleaseChoose: '--- bitte auswählen ---',
    share: 'Teilen',
    shareDescription:
      'Gib deine Aufgabe frei und mache sie online verfügbar. Dazu werden die Daten auf dem Server gespeichert. Durch die Freigabe stimmst du zu, dass die Aufgabe unter {{CC0}} gestellt wird und weiterverwendet werden darf.',
    createLink: 'Link erstellen',
    loading: 'wird geladen ...',
    openInNewTab: 'Link in neuem Tab öffnen',
    back: 'zurück',
    changeSize: 'Größe der Welt ändern',
    startWorld: 'Startwelt',
    endWorld: 'Zielwelt',
    copyStartToEnd: 'Start in Ziel kopieren',
    createNewWorld: 'Neue Welt erstellen',
    width: 'Breite',
    length: 'Länge',
    height: 'Höhe',
    keepWorld: 'Inhalt der Welt behalten',
    create: 'Welt erstellen',
    editOptions: 'Eingabeoptionen',
    all: 'alle erlauben',
    codeOnly: 'nur Code (alle Sprachen)',
    karolOnly: 'nur Karol Code',
    pythonOnly: 'nur Karol-Python-Code [veraltet]',
    javaOnly: 'nur Karol Java',
    pythonProOnly: 'nur Python',
    deleteWorld: 'Welt löschen',
    includeProgram: 'Programm mitspeichern',
    downloadJSON: 'Als JSON herunterladen',
  },
  vm: {
    endlessLoop: 'Hilfe, Karol ist in einer Endlosschleife gefangen!',
    notCompletedPrefix: 'weil',
    notCompletedAnd: ' und ',
    notCompletedBricksTooManyOne: '1 Ziegel zu viel vorhanden ist',
    notCompletedBricksTooMany: '{n} Ziegel zu viel vorhanden sind',
    notCompletedBricksMissingOne: '1 Ziegel fehlt',
    notCompletedBricksMissing: '{n} Ziegel fehlen',
    notCompletedBricksMisplacedOne: '1 Ziegel an der falschen Stelle liegt',
    notCompletedBricksMisplaced: '{n} Ziegel an der falschen Stelle liegen',
    notCompletedMarksTooManyOne: '1 Marke zu viel gesetzt ist',
    notCompletedMarksTooMany: '{n} Marken zu viel gesetzt sind',
    notCompletedMarksMissingOne: '1 Marke fehlt',
    notCompletedMarksMissing: '{n} Marken fehlen',
    notCompletedMarksMisplacedOne: '1 Marke an der falschen Stelle ist',
    notCompletedMarksMisplaced: '{n} Marken an der falschen Stelle sind',
  },
  success: {
    solvedInOneStep: 'Aufgabe gelöst in einem Schritt',
    solvedInSteps: 'Aufgabe gelöst in {n} Schritten',
    saveCode: 'Programmcode speichern',
  },
  character: {
    choose: 'Wähle deine Figur:',
    galleryHint: 'In der Figuren-Galerie findest du viele weitere Figuren.',
  },
  appearance: {
    cancel: 'abbrechen',
    saveAndClose: 'Speichern und schließen',
    brush: 'Pinsel',
    fill: 'Füllen',
    line: 'Linie',
    ellipse: 'Ellipse',
    eraser: 'Radierer',
    undo: 'Rückgängig',
    resetFigure: 'Figur zurücksetzen',
    gallery: 'Figuren-Galerie',
    copyLink: 'Link kopieren',
    clearCanvas: 'Leinwand löschen',
    zoomHint: 'Nutze zum Zoomen Strg + / -',
    linkCopied:
      'Link kopiert! Öffne den Link in einem Browser, um deine Figur zu laden.',
  },
}
