import { enStrings } from './en'

export const deStrings = {
  overview: {
    profile: 'Profil',
    editor: 'Aufgaben-Editor',
    save: 'Speichern',
    saveTooltip: 'In eine Datei speichern',
    load: 'Laden',
    loadTooltip: 'Aus einer Datei laden',
    gameState: 'spielstand',
    lucky: 'Auf gut Glück!',
    version: 'Version: Januar 2024',
    playground: 'Spielwiese',
    imprint: 'Impressum',
    privacy: 'Datenschutz',
    showAll: 'Liste aller Aufgaben',
    closeShowAll: 'Liste aller Aufgaben schließen',
    game: 'Mini-Spiel',
  },
  nameModal: {
    title: 'Herzlich Willkommen!',
    invite: 'Wie lautet dein Name?',
    hint: 'Dein Name wird öffentlich angzeigt.',
    random: 'zufälliger Name',
    start: 'Loslegen!',
  },
  ide: {
    backToOverview: 'zurück zur Übersicht',
    save: 'Speichern',
    blocks: 'Blöcke',
    structogram: 'Struktogramm',
    welcome:
      'Herzlich Willkommen! Hier lernst du Schritt für Schritt die Welt von Karol kennen. Das Tutorial zeigt dir die ersten Grundlagen für die Programmierung.',
    tutorialButton: 'Tutorial anzeigen',
    start: 'Start',
    stop: 'Stopp',
    ready: 'bereit',
    not: 'nicht',
    completed: 'erfüllt',
    back: 'zurück',
    assignments: 'Aufträge',
  },
  profile: {
    title: 'Profil',
    close: 'Schließen',
    username: 'Benutzername',
    noname: 'noch kein Name gesetzt',
    solved: 'Gelöste Aufgaben',
    of: 'von',
    persist: 'Fortschritt dauerhaft auf diesem Gerät speichern',
    reset: 'Fortschritt zurücksetzen',
    resetConfirm: 'Fortschritt jetzt zurücksetzen?',
  },
  highscore: {
    close: 'Schließen',
    rank: 'Platz',
    name: 'Name',
    solved: 'gelöste Aufgaben',
    lastActive: 'zuletzt aktiv',
    sortByActivity: 'sortieren nach letzter Aktivität',
    sortBySolved: 'sortieren nach gelösten Aufgaben',
    currentPlayers: 'Spieler*innen in den letzten 28 Tagen',
    joined: 'beigetreten',
    loading: 'Daten werden geladen ...',
  },
  lucky: {
    description: 'Öffne eine zufällig freigegebene Aufgabe.',
    button: 'Zufällige Aufgabe öffnen',
    hint: 'Die Inhalte sind von NutzerInnen erstellt und lizenzfrei verwendbar.',
    close: 'Schließen',
  },
  outfit: {
    title: 'Passe das Aussehen von Karol an',
    close: 'Schließen',
    cap: 'Kappe',
    shirt: 'Shirt',
    legs: 'Hose',
    skin: 'Hautton',
    suggest: 'Outfit vorschlagen',
  },
  imprint: {
    title: 'Impressum',
    close: 'Schließen',
  },
  quest: {
    warn: '',
  },
}
