export const de2en: { [key: string]: string } = {
  '--- bitte auswählen ---': '--- please choose ---',
  '💫 Aufgaben-Galerie': '💫 Task gallery',
  '2D-Ansicht': '2D view',
  abbrechen: 'cancel',
  abgebrochen: 'aborted',
  abgeschlossen: 'completed',
  'alle erlauben': 'allow all',
  'Als Datei herunterladen': 'Save to a file',
  'Als JSON herunterladen': 'Download as JSON',
  'Aua! Karol ist gegen eine Wand gelaufen.':
    'Karol cannot move in this direction.',
  'Aufgabe aus Datei laden': 'Load exercise from file',
  'Aufgabe freigeben': 'Publish Exercise',
  'Aufgabe gelöst in {n} Schritten': 'Task solved in {n} steps',
  'Aufgabe gelöst in einem Schritt': 'Task solved in one step',
  'Aufgaben-Editor': 'Editor',
  Auftrag: 'Assignment',
  'Auftrag duplizieren': 'Duplicate Task',
  'Auftrag hinzufügen': 'Add Task',
  'Auftrag löschen': 'Delete Task',
  Auftragsvorschau: 'Preview of task',
  'Aus einer Datei laden': 'Load from a file',
  'Aus einer vorhandenen Aufgabe': 'From an existing exercise',
  'Aus freigegebener Aufgabe, gib den vierstelligen Code ein':
    'From a shared exercise, enter the four-character code',
  'Aus Vorlage laden': 'Load from Template',
  'Ausführung beendet': 'End of execution',
  'Ausgabe leeren': 'Clear output',
  'Beachte dass die Daten nicht gespeichert werden. Verlassen?':
    'Your changes will not be saved. Leave?',
  Bearbeiten: 'Edit',
  'Bearbeitung laden': 'Load',
  'Bearbeitung speichern': 'Save',
  bereit: 'ready',
  'Beschreibe, um was es bei der Aufgabe geht ...':
    'Describe what the exercise is about ...',
  'Beschreibung einblenden': 'Show description',
  'Bitte behebe zuerst Probleme!': 'Please fix the problems first!',
  bleiben: 'stay',
  Blöcke: 'Blocks',
  'Blöcke sind nicht zusammenhängend. Verbinde die Blöcke zu einem Programm oder nutze den Hauptprogramm-Block.':
    'Blocks are not connected. Please connect blocks to one program or use use main program block.',
  Breite: 'Width',
  'Code zurücksetzen': 'Reset code',
  Datenschutz: 'Privacy Policy',
  'Dein Fortschritt in guten Händen': 'Your progress is in good hands',
  'Dein Name...': 'Your name...',
  'Die Original-Sprache von Robot Karol':
    'The original language of Robot Karol',
  'die Welt der Algorithmen!': 'the world of algorithms here!',
  Dokumentation: 'Documentation',
  'Editor verlassen': 'Leave Editor',
  Eingabeoptionen: 'Programming modes',
  Einzelschritt: 'Single step',
  Ellipse: 'Ellipse',
  erfüllt: 'completed',
  'Es sind folgende Probleme aufgetreten': 'The following problems occurred',
  Fehler: 'Error',
  'Fehler bei der Generierung des Struktogramms.':
    'Error while generating the structogram.',
  Fertig: 'Done',
  'Figur zeichnen': 'Draw figure',
  'Figur zurücksetzen': 'Reset figure',
  'Figuren-Galerie': 'Figure gallery',
  'Folgende Probleme sind beim Einlesen des Programms aufgetreten:':
    'The following issues occurred while loading the program:',
  'Fortschritt jetzt zurücksetzen? Die Aktion kann nicht rückgängig gemacht werden.':
    'Reset progress now?',
  'Fortschritt laden': 'Import progress',
  'Fortschritt speichern': 'Save progress',
  'Fortschritt zurücksetzen': 'Reset progress',
  'freies Üben': 'Free practice',
  Füllen: 'Fill',
  'Gelösten Aufgaben und deine Programme werden ab jetzt in diesem Browser automatisch gespeichert und sind auch nach dem Schließen des Fensters weiter verfügbar.':
    'Solved tasks and your programs are automatically saved in this browser and remain available even after closing the window.',
  'Gib deine Aufgabe frei und mache sie online verfügbar. Dazu werden die Daten auf dem Server gespeichert. Durch die Freigabe stimmst du zu, dass die Aufgabe unter {{CC0}} gestellt wird und weiterverwendet werden darf.':
    'Share your task and make it available online. The data will be stored on the server. By sharing, you agree to release the exercise under {{CC0}} and allow it to be reused.',
  'Größe der Welt ändern': 'Change World Size',
  'Hallo, {name}!': 'Hello, {name}!',
  Hauptprogramm: 'Main program',
  'Herzlich Willkommen! Hier lernst du Schritt für Schritt die Welt von Karol kennen. Das Tutorial zeigt dir die ersten Grundlagen für die Programmierung.':
    "Welcome! Here, you'll step by step get to know the world of Karol. The tutorial will guide you through the fundamental aspects of programming.",
  'Hilfe, Karol ist in einer Endlosschleife gefangen!':
    'Help, Karol is stuck in an infinite loop!',
  hoch: 'Up',
  Höhe: 'Height',
  Impressum: 'Imprint',
  'In der Figuren-Galerie findest du viele weitere Figuren.':
    'You can find many more figures in the figure gallery.',
  'In Zwischenablage kopiert!': 'Copied to clipboard!',
  'Inhalt der Welt behalten': 'Keep World Contents',
  'Karol kann diese Höhe nicht überwinden.':
    'Karol cannot overcome this height.',
  'Karol kann hier keine Ziegel aufheben.':
    'Karol cannot pick up a brick here.',
  'Karol kann hier keinen Quader aufstellen.':
    'Karol cannot place a block here.',
  'Karol kann hier keinen Ziegel aufstellen.':
    'Karol cannot place a brick here.',
  'Karol kann keinen Quader auf eine Marke stellen.':
    'Karol cannot place a block on a mark.',
  'Karol kann keinen Quader auf Ziegel stellen.':
    'Karol cannot place a block on a brick.',
  'Keine Ziegel zum Aufheben': 'No bricks to pick up.',
  'Klicke auf Start!': 'Click Start!',
  Laden: 'Load',
  Länge: 'Length',
  'Leeres Programm': 'Empty program',
  'Legen wir los! Ziehe den Befehl „Schritt" auf die Arbeitsfläche':
    'Let\'s get started! Drag the "step" command onto the workspace',
  'Leinwand löschen': 'Clear canvas',
  Lernpfad: 'Learning path',
  Linie: 'Line',
  'Link erstellen': 'Create Link',
  'Link in neuem Tab öffnen': 'Open Link in New Tab',
  'Link kopieren': 'Copy link',
  'Link kopiert! Öffne den Link in einem Browser, um deine Figur zu laden.':
    'Link copied! Open the link in a browser to load your figure.',
  LinksDrehen: 'turn left',
  'Loslegen!': 'Get started!',
  mal: 'times',
  'Material für Lehrkräfte': 'Material for teachers',
  'Maximale Stapelhöhe erreicht.': 'Maximum stack height reached.',
  'Mehr als ein Hauptprogramm - erwarte höchstens ein Hauptprogramm.':
    'More than one main program, expecting at most one main program.',
  Menü: 'Menu',
  'Neue Figur verfügbar:': 'New figure available:',
  'Neue Welt erstellen': 'Create New World',
  'Neuer Auftrag': 'New Task',
  nicht: 'not',
  'nur Code (alle Sprachen)': 'code only (all languages)',
  'nur Karol Code': 'karol code only',
  'nur Karol Java': 'java only',
  'nur Python': 'python pro only',
  'Nutze zum Zoomen Strg + / -': 'Use Ctrl + / - to zoom',
  OK: 'OK',
  Pinsel: 'Brush',
  'Probleme im Programm': 'Problems in the program',
  Programm: 'Program',
  'Programm unvollständig': 'Incomplete program',
  'Programm wird ausgeführt': 'Running program',
  'Programm wird eingelesen ...': 'Loading program ...',
  'Programmcode speichern': 'Save program code',
  'Programmiere frei und baue dein Herzensprojekt.':
    'Program freely and build your passion project.',
  Radierer: 'Eraser',
  RechtsDrehen: 'turn right',
  Rückgängig: 'Undo',
  runter: 'Down',
  Schließen: 'Close',
  schließen: 'close',
  Schritt: 'step',
  'Schritte pro Sekunde': 'steps per second',
  'Sehr gut! Schreibe das Programm fertig: Gehe mit Karol zwei Schritte und lege einen Ziegel.':
    'Great! Finish the program: make Karol take two steps and set down a brick.',
  'Speichern und schließen': 'Save and close',
  Spenden: 'Donate',
  Spickzettel: 'Cheat sheet',
  spielstand: 'gamestate',
  Spielwiese: 'Playground',
  'Start in Ziel kopieren': 'Copy Start to End',
  Startwelt: 'Start World',
  Struktogramm: 'Structogram',
  'Tasten:': 'Keys:',
  Teilen: 'Share',
  Testen: 'Test',
  'Titel der Aufgabe': 'Title of the Exercise',
  'Tutorial anzeigen': 'Show Tutorial',
  'Variablen:': 'Variables:',
  'Video-Erklärungen': 'Video explanations',
  Vollbild: 'Fullscreen',
  Vorschau: 'Preview',
  'Wähle deine Figur:': 'Choose your figure:',
  weiter: 'continue',
  Weiter: 'Continue',
  Welt: 'World',
  'Welt bearbeiten': 'Edit World',
  'Welt erstellen': 'Create World',
  'Welt löschen': 'Delete World Content',
  'Wie heißt du?': 'What is your name?',
  wiederhole: 'repeat',
  'wiederhole immer': 'repeat always',
  'wiederhole solange': 'repeat while',
  'Willkommen 👋 entdecke hier': 'Welcome 👋 discover',
  'wird geladen ...': 'loading ...',
  Zeile: 'Line',
  Zielwelt: 'End World',
  'Zur deutsche Version': 'Switch to German Version',
  Zurück: 'back',
  zurück: 'Back',
}
