export const de2en: { [key: string]: string } = {
  '💫 Aufgaben-Galerie': '💫 Task gallery',
  'Als Datei herunterladen': 'Save to a file',
  'Aufgabe aus Datei laden': 'Load exercise from file',
  'Aufgaben-Editor': 'Editor',
  'Aus einer Datei laden': 'Load from a file',
  Datenschutz: 'Privacy Policy',
  'die Welt der Algorithmen!': 'the world of algorithms here!',
  Dokumentation: 'Documentation',
  'Figur zeichnen': 'Draw figure',
  'Figuren-Galerie': 'Figure gallery',
  'Fortschritt laden': 'Import progress',
  'Fortschritt speichern': 'Export progress',
  'Fortschritt zurücksetzen': 'Reset progress',
  'freies Üben': 'Free practice',
  Impressum: 'Imprint',
  Laden: 'Load',
  Lernpfad: 'Learning path',
  'Material für Lehrkräfte': 'Material for teachers',
  'Neue Figur verfügbar:': 'New figure available:',
  schließen: 'close',
  Spenden: 'Donate',
  Spielwiese: 'Playground',
  'Video-Erklärungen': 'Video explanations',
  'Willkommen 👋 entdecke hier': 'Welcome 👋 discover',
  'Zur deutsche Version': 'Switch to German Version',
}
