import { deStrings } from './de'

export const enStrings: typeof deStrings = {
  overview: {
    profile: 'Profile',
    editor: 'Editor',
    save: 'Export progress',
    saveTooltip: 'Save to a file',
    load: 'Import progress',
    loadTooltip: 'Load from a file',
    gameState: 'gamestate',
    playground: 'Playground',
    imprint: 'Imprint',
    privacy: 'Privacy Policy',
    showAll: 'List of all tasks',
    closeShowAll: 'Close List of all tasks',
    game: 'Mini-Game',
    storeOnDevice: 'Save progress on this device?',
    later: 'later',
    docs: 'Documentation',
    path: 'Self-learning path',
    startNow: 'Start now',
    syncProgress: 'Save progress',
    syncTitle: 'Your progress is in good hands',
    syncBody:
      'Solved tasks and your programs are automatically saved in this browser and remain available even after closing the window.',
    donate: 'Donate',
    learningPath: 'Learning path',
    freePractice: 'Free practice',
    loadQuestFromFile: 'Load exercise from file',
    welcome1: 'Welcome 👋 discover',
    welcome2: 'the world of algorithms here!',
    drawFigure1: 'Draw',
    drawFigure2: 'figure',
    figureGallery: 'Figure gallery',
    taskGallery: '💫 Task gallery',
    teacherMaterial: 'Material for teachers',
    videoExplanations: 'Video explanations',
    switchToGerman: 'Switch to German Version',
    newFigureAvailable: 'New figure available:',
    close: 'close',
    loadFigure: 'Load',
    greeting: 'Hello, {name}!',
    playgroundDescription: 'Program freely and build your passion project.',
  },
  nameModal: {
    title: 'Welcome!',
    invite: 'What is your name?',
    hint: 'Your name will be displayed publicly.',
    random: 'random name',
    start: 'Get started!',
    placeholder: 'Your name...',
  },
  ide: {
    backToOverview: 'Back to overview',
    save: 'Save',
    load: 'Load',
    blocks: 'Blocks',
    structogram: 'Structogram',
    welcome:
      "Welcome! Here, you'll step by step get to know the world of Karol. The tutorial will guide you through the fundamental aspects of programming.",
    tutorialButton: 'Show Tutorial',
    start: 'Start',
    stop: 'Stop',
    ready: 'ready',
    not: 'not',
    completed: 'completed',
    back: 'back',
    assignment: 'Assignment',
    assignments: 'Assignments',
    continue: 'Continue',
    done: 'Done',
    continueAll: 'continue (test all assignments)',
    steps: 'steps per second',
    programError: 'Incomplete program',
    loading: 'Loading program ...',
    running: 'Running program',
    error: 'Error',
    endOfRun: 'End of execution',
    aborted: 'aborted',
    clear: 'Clear output',
    taskCompleted: 'completed',
    showDescription: 'Show description',
    thereAreErrors: 'The following issues occurred while loading the program:',
    close: 'Close',
    connectAll:
      'Blocks are not connected. Please connect blocks to one program or use use main program block.',
    multipleMains:
      'More than one main program, expecting at most one main program.',
    stay: 'stay',
    exit: 'continue',
    read: 'Read the instructions',
    language: 'Language',
    problems: 'The following problems occurred',
    line: 'Line',
    preview: 'Preview of task',
    step: 'Single step',
    continueProgram: 'continue',
    blockExplainer: 'Drag blocks onto the workspace and connect them.',
    menu: 'Menu',
    openInEditor: 'Open in editor',
    resetCode: 'Reset code',
    program: 'Program',
    world: 'World',
    ok: 'OK',
    tourStepDrag:
      'Let\'s get started! Drag the "step" command onto the workspace',
    tourClickStart: 'Click Start!',
    tourComplete:
      'Great! Finish the program: make Karol take two steps and set down a brick.',
    fixProblemsFirst: 'Please fix the problems first!',
    originalLanguage: 'The original language of Robot Karol',
    cheatsheet: 'Cheat sheet',
    variables: 'Variables:',
    mainProgram: 'Main program',
    problemsInProgram: 'Problems in the program',
    emptyProgram: 'Empty program',
    structogramError: 'Error while generating the structogram.',
    repeatForever: 'repeat always',
    repeatWhile: 'repeat while',
    repeat: 'repeat',
    times: 'times',
    view2D: '2D view',
    fullscreen: 'Fullscreen',
    keys: 'Keys:',
    manualStep: 'step',
    manualTurnLeft: 'turn left',
    manualTurnRight: 'turn right',
    manualBack: 'back',
    questPromptContinue: 'continue',
    copiedToClipboard: 'Copied to clipboard!',
  },
  profile: {
    title: 'Profile',
    close: 'Close',
    username: 'Username',
    noname: 'No name set yet',
    solved: 'Solved Tasks',
    of: 'of',
    reset: 'Reset progress',
    resetConfirm: 'Reset progress now?',
  },
  imprint: {
    title: 'Imprint',
    close: 'Close',
  },
  crash: {
    invalidMove: 'Karol cannot move in this direction.',
    invalidHeight: 'Karol cannot overcome this height.',
    invalidBrick: 'Karol cannot place a brick here.',
    maxHeight: 'Maximum stack height reached.',
    invalidPick: 'Karol cannot pick up a brick here.',
    noBricks: 'No bricks to pick up.',
    invalidBlock: 'Karol cannot place a block here.',
    noBlockOnBrick: 'Karol cannot place a block on a brick.',
    noBlockOnMark: 'Karol cannot place a block on a mark.',
  },
  quest: {
    warn: 'The text mode is not translated yet and only available in German. You can proceed anyways.',
  },
  editor: {
    edit: 'Edit',
    preview: 'Preview',
    leave: 'Leave Editor',
    leaveWarning: 'Your changes will not be saved. Leave?',
    title: 'Title of the Exercise',
    description: 'Describe what the exercise is about ...',
    newTask: 'New Task',
    test: 'Test',
    editWorld: 'Edit World',
    up: 'Up',
    down: 'Down',
    duplicate: 'Duplicate Task',
    delete: 'Delete Task',
    addTask: 'Add Task',
    publish: 'Publish Exercise',
    loadFrom: 'Load from Template',
    load: 'Load',
    close: 'Close',
    fromCode: 'From a shared exercise, enter the four-character code',
    fromQuest: 'From an existing exercise',
    pleaseChoose: '--- please choose ---',
    share: 'Share',
    shareDescription:
      'Share your task and make it available online. The data will be stored on the server. By sharing, you agree to release the exercise under {{CC0}} and allow it to be reused.',
    createLink: 'Create Link',
    loading: 'loading ...',
    openInNewTab: 'Open Link in New Tab',
    back: 'Back',
    changeSize: 'Change World Size',
    startWorld: 'Start World',
    endWorld: 'End World',
    copyStartToEnd: 'Copy Start to End',
    createNewWorld: 'Create New World',
    width: 'Width',
    length: 'Length',
    height: 'Height',
    keepWorld: 'Keep World Contents',
    create: 'Create World',
    editOptions: 'Programming modes',
    all: 'allow all',
    codeOnly: 'code only (all languages)',
    karolOnly: 'karol code only',
    pythonOnly: 'python only',
    pythonProOnly: 'python pro only',
    javaOnly: 'java only',
    deleteWorld: 'Delete World Content',
    includeProgram: 'Include program',
    downloadJSON: 'Download as JSON',
  },
  vm: {
    endlessLoop: 'Help, Karol is stuck in an infinite loop!',
    notCompletedPrefix: 'because',
    notCompletedAnd: ' and ',
    notCompletedBricksTooManyOne: '1 brick too many',
    notCompletedBricksTooMany: '{n} bricks too many',
    notCompletedBricksMissingOne: '1 brick missing',
    notCompletedBricksMissing: '{n} bricks missing',
    notCompletedBricksMisplacedOne: '1 brick is in the wrong place',
    notCompletedBricksMisplaced: '{n} bricks are in the wrong place',
    notCompletedMarksTooManyOne: '1 mark is set too many times',
    notCompletedMarksTooMany: '{n} marks are set too many times',
    notCompletedMarksMissingOne: '1 mark missing',
    notCompletedMarksMissing: '{n} marks missing',
    notCompletedMarksMisplacedOne: '1 mark is in the wrong place',
    notCompletedMarksMisplaced: '{n} marks are in the wrong place',
  },
  success: {
    solvedInOneStep: 'Task solved in one step',
    solvedInSteps: 'Task solved in {n} steps',
    saveCode: 'Save program code',
  },
  character: {
    choose: 'Choose your figure:',
    galleryHint: 'You can find many more figures in the figure gallery.',
  },
  appearance: {
    cancel: 'cancel',
    saveAndClose: 'Save and close',
    brush: 'Brush',
    fill: 'Fill',
    line: 'Line',
    ellipse: 'Ellipse',
    eraser: 'Eraser',
    undo: 'Undo',
    resetFigure: 'Reset figure',
    gallery: 'Figure gallery',
    copyLink: 'Copy link',
    clearCanvas: 'Clear canvas',
    zoomHint: 'Use Ctrl + / - to zoom',
    linkCopied: 'Link copied! Open the link in a browser to load your figure.',
  },
}
