// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {nestedComment} from "./nestedComment"
import {keywords} from "./keywords"
const spec_idx = {__proto__:null,LinksDrehen:76, linksdrehen:78, linksDrehen:80, Linksdrehen:82, RechtsDrehen:84, rechtsdrehen:86, rechtsDrehen:88, Rechtsdrehen:90, MarkeSetzen:92, markesetzen:94, markeSetzen:96, Markesetzen:98, "MarkeLöschen":100, "markelöschen":102, "markeLöschen":104, "Markelöschen":106, Beenden:108, beenden:110, Schritt:118, schritt:120, Hinlegen:122, hinlegen:124, Aufheben:126, aufheben:128, IstWand:132, istwand:134, Istwand:136, istWand:138, NichtIstWand:140, nichtistwand:142, Nichtistwand:144, IstZiegel:146, istziegel:148, istZiegel:150, Istziegel:152, NichtIstZiegel:154, nichtistziegel:156, Nichtistziegel:158, IstMarke:160, istmarke:162, istMarke:164, Istmarke:166, NichtIstMarke:168, nichtistmarke:170, Nichtistmarke:172, IstNorden:174, istnorden:176, istNorden:178, Istnorden:180, NichtIstNorden:182, nichtistnorden:184, Nichtistnorden:186}
export const parser = LRParser.deserialize({
  version: 14,
  states: "(|QfQROOOOQQ'#DQ'#DQOOQQ'#Dh'#DhO%uQRO'#CoO%|QRO'#CoO&TQRO'#CoO&YQRO'#CrO&eQRO'#CuOOQQ'#Cv'#CvOOQQ'#DP'#DPO(_QRO'#CwOOQQ'#Cy'#CyQfQROOO(dQRO,59ZO(iQRO,59ZOxQRO,59ZOOQQ'#Ct'#CtO&eQRO,59^O(qQRO,59^O(vQRO,59^OOQQ'#Cs'#CsO)^QRO'#CsO+dQRO,59aOOQQ'#Cx'#CxO+iQRO,59cOOQQ-E6w-E6wOOQQ1G.u1G.uOOQQ'#Cq'#CqO,PQRO1G.uO.eQRO1G.uO.lQRO1G.uO.sQRO1G.xOOQQ'#Cz'#CzO.sQRO1G.xOOQQ1G.x1G.xO(lQRO,59_O/ZQRO1G.{O/tQRO1G.}OOQQ1G.}1G.}OOQQ7+$a7+$aO0[QRO7+$aO0aQRO7+$aO0iQRO7+$dOOQQ7+$d7+$dOOQQ-E6x-E6xO1PQRO1G.yO1UQRO7+$gOOQQ7+$g7+$gO1oQRO7+$gOOQQ7+$i7+$iOOQQ<<G{<<G{O2VQRO<<G{OOQQ<<HO<<HOOOQQ7+$e7+$eOOQQ<<HR<<HRO2[QRO<<HRO2[QRO<<HROOQQAN=gAN=gO2rQROAN=mOOQQAN=mAN=mOOQQG23XG23X",
  stateData: "3Y~OPOSqOS_OS`OSaOSrOS~OQXORUOWVO[YO^TOuWOvPOwPOxPOyPOzPO{PO|PO}PO!OPO!PPO!QPO!RPO!SPO!TPO!UPO!VPO!WPO!XPO!]QO!^QO!_QO!`QO!aQO!bQO~OQcXRcXWcX[cX^cXocXucXvcXwcXxcXycXzcX{cX|cX}cX!OcX!PcX!QcX!RcX!ScX!TcX!UcX!VcX!WcX!XcX!]cX!^cX!_cX!`cX!acX!bcXScX]cXYcXZcX~O!Y]O~P#fO!Y^O~P#fOd_O~OTaOVcO!c`O~O!ddO!edO!fdO!gdO!hdO!idO!jdO!keO!leO!meO!neO!oeO!peO!qeO!rdO!sdO!tdO!udO!vdO!wdO!xdO!ydO!zdO!{dO!|dO!}dO#OdO#PdO~OugO~O!ZjO~O!ZjO!ckO~OUoO~OQXORUOSrOWVO^TOuWO~PxO!YsOXgXQgXRgXSgXWgX^gXugXvgXwgXxgXygXzgX{gX|gX}gX!OgX!PgX!QgX!RgX!SgX!TgX!UgX!VgX!WgX!XgX!]gX!^gX!_gX!`gX!agX!bgX~OXtO~OQXORUOWVO]vO^TOuWO~PxO!ZwO~OQciRciWci[ci^ciociucivciwcixciycizci{ci|ci}ci!Oci!Pci!Qci!Rci!Sci!Tci!Uci!Vci!Wci!Xci!]ci!^ci!_ci!`ci!aci!bciSci]ciYciZci~O!YxO~P,UO!YyO~P,UOQXORUOS{OWVO^TOuWO~PxOQXORUOWVOY!POZ!QO^TOuWO~PxOQXORUOWVO]!RO^TOuWO~PxO!Z!SO~O!Z!SO!ckO~OQXORUOS!UOWVO^TOuWO~PxO!Z!VO~OQXORUOWVOY!WOZ!XO^TOuWO~PxOQXORUOWVOY!WO^TOuWO~PxO!Z!ZO~OQXORUOWVOY!]O^TOuWO~PxOQXORUOWVOY!^O^TOuWO~PxO",
  goto: "%T!]PPPPPPPPPPPPPPPPPPP!^P!n!^!w!}!^!^#Q#U#X#_PPPP#y$]PPPPPPPPPPPPPPPPPPPPP$pmXO[choqtuz!O!Q!X!Y![Ql^Q}sR!TyQfVRoaRbUTZO[RhYQ[ORi[QqcQuhQzo[|quz!O!Y![Q!OtQ!Y!QR![!XSZO[ipchoqtuz!O!Q!X!Y![lRO[choqtuz!O!Q!X!Y![Rm_lSO[choqtuz!O!Q!X!Y![Rn_",
  nodeNames: "⚠ Comment Return RepeatStart RepeatEnd RepeatWhileKey RepeatTimesKey RepeatAlwaysKey IfKey ThenKey IfEndKey ElseKey CmdStart CmdEnd KarolPrefix LineComment PythonComment BlockComment Program Command . Parameter Repeat Condition Times IfThen CustomRef Cmd CmdName",
  maxTerm: 93,
  nodeProps: [
    ["closedBy", 3,"RepeatEnd",8,"IfEndKey",12,"CmdEnd"]
  ],
  skippedNodes: [0,1,15,16,17],
  repeatNodeCount: 2,
  tokenData: "']~ReXY!dYZ!d]^!dpq!dst!uxy#^yz#c!O!P#h!P!Q#m!Q![%f!]!^'W!c!}&`#R#S&`#T#o&`%[%]&`%n%o&`%t%u&`%w%x&`%|%}&`&`&a&`&f&g&`~!iSq~XY!dYZ!d]^!dpq!d~!zS`~OY!uZ;'S!u;'S;=`#W<%lO!u~#ZP;=`<%l!u~#cO!Y~~#hO!Z~~#mOd~~#pQz{#v!P!Q$}~#yTOz#vz{$Y{;'S#v;'S;=`$w<%lO#v~$]VOz#vz{$Y{!P#v!P!Q$r!Q;'S#v;'S;=`$w<%lO#v~$wOa~~$zP;=`<%l#v~%SS_~OY$}Z;'S$};'S;=`%`<%lO$}~%cP;=`<%l$}~%mZ!c~u~!Q![%f!c!}&`#R#S&`#T#o&`%[%]&`%n%o&`%t%u&`%w%x&`%|%}&`&`&a&`&f&g&`~&eZu~!Q![&`!c!}&`#R#S&`#T#o&`%[%]&`%n%o&`%t%u&`%w%x&`%|%}&`&`&a&`&f&g&`~']Or~",
  tokenizers: [0, nestedComment],
  topRules: {"Program":[0,18]},
  specialized: [{term: 37, get: (value, stack) => (keywords(value, stack) << 1), external: keywords},{term: 37, get: value => spec_idx[value] || -1}],
  tokenPrec: 0
})
