// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {nestedComment} from "./nestedComment"
const spec_idx = {__proto__:null,Schritt:58, schritt:60, LinksDrehen:62, linksdrehen:64, linksDrehen:66, Linksdrehen:68, RechtsDrehen:70, rechtsdrehen:72, rechtsDrehen:74, Rechtsdrehen:76, Hinlegen:78, hinlegen:80, Aufheben:82, aufheben:84, MarkeSetzen:86, markesetzen:88, markeSetzen:90, Markesetzen:92, "MarkeLöschen":94, "markelöschen":96, "markeLöschen":98, "Markelöschen":100, Beenden:102, beenden:104, Unterbrechen:106, unterbrechen:108, wiederhole:110, solange:112, IstWand:114, istwand:116, Istwand:118, istWand:120, NichtIstWand:122, nichtistwand:124, Nichtistwand:126, IstZiegel:128, istziegel:130, istZiegel:132, Istziegel:134, NichtIstZiegel:136, nichtistziegel:138, Nichtistziegel:140, IstMarke:142, istmarke:144, istMarke:146, Istmarke:148, NichtIstMarke:150, nichtistmarke:152, Nichtistmarke:154, mal:158, endewiederhole:160, endeWiederhole:162, wenn:164, dann:166, sonst:168, endewenn:170, endeWenn:172, Anweisung:174, anweisung:176, endeAnweisung:178, endeanweisung:180}
export const parser = LRParser.deserialize({
  version: 14,
  states: "(^Q]QROOOOQQ'#C`'#C`OOQQ'#Cb'#CbO#`QRO'#CaOOQQ'#Ci'#CiO$uQRO'#ChOOQQ'#Cm'#CmOOQQ'#Cw'#CwOOQQ'#Co'#CoO$|QRO'#CnOOQQ'#Cr'#CrQ]QROOOOQQ'#Cc'#CcOOQQ'#Ce'#CeO%RQRO,58{O'WQRO,58{OOQQ'#Cd'#CdO']QRO'#CdOOQQ'#Cj'#CjO'bQRO,59SO)hQRO,59SOOQQ'#Cp'#CpO)mQRO,59YOOQQ-E6p-E6pOOQQ'#Cs'#CsO+pQRO1G.gOOQQ'#Cg'#CgOOQQ1G.g1G.gO+pQRO1G.gOOQQ'#Cf'#CfO-sQRO,59OO'bQRO1G.nOOQQ'#Ck'#CkOOQQ'#Cl'#ClOOQQ1G.n1G.nO-xQRO1G.nO'bQRO1G.nO)mQRO1G.tOOQQ'#Cq'#CqOOQQ1G.t1G.tOOQQ-E6q-E6qOOQQ7+$R7+$RO+pQRO7+$ROOQQ1G.j1G.jOOQQ7+$Y7+$YO-xQRO7+$YO-xQRO7+$YO'bQRO7+$YOOQQ7+$`7+$`OOQQ<<Gm<<GmO-xQRO<<GtOOQQ<<Gt<<GtO-xQRO<<GtOOQQAN=`AN=`O-xQROAN=`OOQQG22zG22z",
  stateData: "/{~OPOSjOSQOS~OlUOmPOnPOoPOpPOqPOrPOsPOtPOuPOvPOwPOxPOyPOzPO{PO|PO}PO!OPO!PPO!QPO!RPO!SPO!TPO!UPO!VPO!WPO!XQO!tSO!yWO!zWO~O!Y[O!p]O~O!Z`O![`O!]`O!^`O!_`O!``O!a`O!b`O!c`O!d`O!e`O!f`O!g`O!h`O!i`O!j`O!k`O!l`O!maO~O!ubO~P#hOleO~OlUOmPOnPOoPOpPOqPOrPOsPOtPOuPOvPOwPOxPOyPOzPO{PO|PO}PO!OPO!PPO!QPO!RPO!SPO!TPO!UPO!VPO!WPO!XQO!rjO!sjO!tSO~P#hO!qmO~O!nnO~OlUOmPOnPOoPOpPOqPOrPOsPOtPOuPOvPOwPOxPOyPOzPO{PO|PO}PO!OPO!PPO!QPO!RPO!SPO!TPO!UPO!VPO!WPO!XQO!tSO!vpO!wqO!xqO~O!ubO~OlUOmPOnPOoPOpPOqPOrPOsPOtPOuPOvPOwPOxPOyPOzPO{PO|PO}PO!OPO!PPO!QPO!RPO!SPO!TPO!UPO!VPO!WPO!XQO!tSO!{vO!|vO~OlUOmPOnPOoPOpPOqPOrPOsPOtPOuPOvPOwPOxPOyPOzPO{PO|PO}PO!OPO!PPO!QPO!RPO!SPO!TPO!UPO!VPO!WPO!XQO!rjO!sjO!tSO~O!o{O~OlUOmPOnPOoPOpPOqPOrPOsPOtPOuPOvPOwPOxPOyPOzPO{PO|PO}PO!OPO!PPO!QPO!RPO!SPO!TPO!UPO!VPO!WPO!XQO!tSO!wqO!xqO~O",
  goto: "%}lPPPPmm!R!g!j!p!s!vm#Q#f#l#vm$[$`$d$g$m$sPPP%guVOZ^cfilostuz}!O!P!S!U!WuROZ^cfilostuz}!O!P!S!U!WR^RQdTRl^R_RRl_Qk^SyilR!RzuTOZ^cfilostuz}!O!P!S!U!WQcTRtdQscS}otR!U!PQrcU|ostU!T}!O!PS!V!S!UR!X!WTYOZTXOZRfXQwfR!QuQZORgZQi^QocQuf`xiouz!O!P!S!WQzlQ!OsQ!PtQ!S}R!W!USYOZqh^cfilostuz}!O!P!S!U!W",
  nodeNames: "⚠ Comment LineComment Program Command Repeat RepeatStart RepeatWhileKey Condition Times RepeatTimesKey RepeatEnd IfThen IfKey ThenKey ElseKey IfEndKey CustomRef Cmd CmdStart CmdName CmdEnd",
  maxTerm: 90,
  nodeProps: [
    ["closedBy", 6,"RepeatEnd",13,"IfEndKey",19,"CmdEnd"]
  ],
  skippedNodes: [0,1,2],
  repeatNodeCount: 2,
  tokenData: "$i~R`XY!TYZ!T]^!Tpq!T!P!Q!f!Q![!w!c!}#q#R#S#q#T#o#q%[%]#q%n%o#q%t%u#q%w%x#q%|%}#q&`&a#q&f&g#q~!YSj~XY!TYZ!T]^!Tpq!T~!iP!P!Q!l~!qQQ~OY!lZ~!l~#OZ!p~l~!Q![!w!c!}#q#R#S#q#T#o#q%[%]#q%n%o#q%t%u#q%w%x#q%|%}#q&`&a#q&f&g#q~#vZl~!Q![#q!c!}#q#R#S#q#T#o#q%[%]#q%n%o#q%t%u#q%w%x#q%|%}#q&`&a#q&f&g#q",
  tokenizers: [0, nestedComment],
  topRules: {"Program":[0,3]},
  specialized: [{term: 28, get: value => spec_idx[value] || -1}],
  tokenPrec: 0
})
