// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {nestedComment} from "./nestedComment"
import {keywords} from "./keywords"
export const parser = LRParser.deserialize({
  version: 14,
  states: "(pQcQROOO!rQRO'#CqO!yQRO'#CqO#QQRO'#CqO#VQRO'#CtO#bQRO'#CwOOQQ'#Cx'#CxOOQQ'#DR'#DRO#jQRO'#CyOOQQ'#C{'#C{QcQROOO#oQRO,59]O#tQRO,59]O#|QRO,59]OOQQ'#Cv'#CvO#bQRO,59`O$UQRO,59`O$oQRO,59`OOQQ'#Cu'#CuO$vQRO'#CuO%eQRO,59cOOQQ'#Cz'#CzO%jQRO,59eOOQQ-E6y-E6yOOQQ1G.w1G.wOOQQ'#Cs'#CsO%qQRO1G.wO&nQRO1G.wO&uQRO1G.wO&|QRO1G.zOOQQ'#C|'#C|O&|QRO1G.zOOQQ1G.z1G.zO#wQRO,59aO'TQRO1G.}O'_QRO1G/POOQQ1G/P1G/POOQQ7+$c7+$cO'fQRO7+$cO'kQRO7+$cO'sQRO7+$fOOQQ7+$f7+$fOOQQ-E6z-E6zO'zQRO1G.{O(PQRO7+$iOOQQ7+$i7+$iO(ZQRO7+$iOOQQ7+$k7+$kOOQQ<<G}<<G}O(bQRO<<G}OOQQ<<HQ<<HQOOQQ7+$g7+$gOOQQ<<HT<<HTO(gQRO<<HTO(gQRO<<HTOOQQAN=iAN=iO(nQROAN=oOOQQAN=oAN=oOOQQG23ZG23Z",
  stateData: "(x~OPOSsOSbOScOStOS~OQSOVTOZWO]RO`QOaPOyUO~OQeXVeXZeX]eX`eXaeXqeXyeXReX[eXXeXYeX~OvZO~PzOv[O~PzOf]O~OS_OUaOx^O~O^bO_cO~OyeO~OwhO~OwhOxiO~O`lOakO~OTmO~OQSOVTO]RO`QOaPOyUO~ORpO~P$ZOvqOWiXQiXRiXViX]iX`iXaiXyiX~OWrO~O[tO~P$ZOwuO~OQeiVeiZei]ei`eiaeiqeiyeiRei[eiXeiYei~OvvO~P%vOvwO~P%vORyO~P$ZOX}OY!OO~P$ZO[!PO~P$ZOw!QO~Ow!QOxiO~OR!SO~P$ZOw!TO~OX!UOY!VO~P$ZOX!UO~P$ZOw!XO~OX!ZO~P$ZOX![O~P$ZOxy~",
  goto: "#vvPPPPPPPPPPPPPPPPPPPPPwP!Xw!b!hww!k!o!r!xPPPP#dmVOYafmorsx|!O!V!W!YQj[Q{qR!RwQdTRm_R`STXOYRfWQYORgYQoaQsfQxm[zosx|!W!YQ|rQ!W!OR!Y!VSXOYinafmorsx|!O!V!W!Y",
  nodeNames: "⚠ Comment RepeatStart RepeatEnd RepeatWhileKey RepeatTimesKey RepeatAlwaysKey IfKey ThenKey IfEndKey ElseKey CmdStart CmdEnd KarolPrefix ConditionWithoutParam ConditionMaybeWithParam CommandWithParameter CommandPure LineComment BlockComment Program Command . Parameter Repeat Condition Times IfThen CustomRef Cmd CmdName",
  maxTerm: 41,
  nodeProps: [
    ["closedBy", 2,"RepeatEnd",7,"IfEndKey",11,"CmdEnd"]
  ],
  skippedNodes: [0,1,18,19],
  repeatNodeCount: 2,
  tokenData: "&z~ReXY!dYZ!d]^!dpq!dxy!uyz!zz{#P!O!P#z!P!Q$P!Q![%x!]!^&u!c!}#P#R#S#P#T#o#P%[%]#P%n%o#P%t%u#P%w%x#P%|%}#P&`&a#P&f&g#P~!iSs~XY!dYZ!d]^!dpq!d~!zOv~~#POw~~#U[y~z{#P!Q![#P!c!}#P#R#S#P#T#o#P%[%]#P%n%o#P%t%u#P%w%x#P%|%}#P&`&a#P&f&g#P~$POf~~$SQz{$Y!P!Q%a~$]TOz$Yz{$l{;'S$Y;'S;=`%Z<%lO$Y~$oVOz$Yz{$l{!P$Y!P!Q%U!Q;'S$Y;'S;=`%Z<%lO$Y~%ZOc~~%^P;=`<%l$Y~%fSb~OY%aZ;'S%a;'S;=`%r<%lO%a~%uP;=`<%l%a~&P[x~y~z{#P!Q![%x!c!}#P#R#S#P#T#o#P%[%]#P%n%o#P%t%u#P%w%x#P%|%}#P&`&a#P&f&g#P~&zOt~",
  tokenizers: [0, nestedComment],
  topRules: {"Program":[0,20]},
  specialized: [{term: 41, get: (value, stack) => (keywords(value, stack) << 1), external: keywords}],
  tokenPrec: 359
})
