name: E2E Tests

on:
  workflow_dispatch:
  push:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # if /src-e2e constains the string Scenario.only, fail the job
      - name: Check for Scenario.only
        run: |
          if grep -q "Scenario.only" src-e2e/**/*.ts; then
            echo "Scenario.only found in src-e2e, failing the job."
            exit 1
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install Dependencies
        run: |
          npm install
          npm run build

      - name: Start Server
        run: |
          nohup npm start &  # Startet den Server im Hintergrund
          sleep 5           # Kurze Pause, damit der Server Zeit zum Starten hat

      - name: Run E2E Tests
        working-directory: src-e2e
        run: |
          npm install
          npx playwright install firefox chromium
          HEADLESS=true npm run test:all
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: e2e-screenshots-on-fail
          path: src-e2e/output/ # or path/to/artifact
